name: Update BGG collection

on:
  workflow_dispatch:   # ручной запуск
  schedule:
    - cron: '0 12 * * *'  # ежедневный запуск в 12:00 UTC (по желанию)

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Забираем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Настраиваем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: pip install requests

      # 4️⃣ Запускаем скрипт для скачивания коллекции
      - name: Fetch BGG collection
        run: |
          python scripts/fetch_bgg_collection.py --username "Antropophag" --out data/games.json

      # 5️⃣ Коммитим и пушим JSON с токеном
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # убедись, что секрет существует в этом репо
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # используем токен для HTTPS авторизации
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/Antropophag/my-boardgames.git
          git add -f data/games.json
          git commit -m "Update BGG collection" || echo "No changes to commit"
          git push origin main
